version: '3'
services:

  azure-storage:
    image: azure-storage
    build: 
      context: ./projects/azure-storage
      dockerfile: Dockerfile
    container_name: video-storage # abstraction (not relevant where it gets videos from (Azure in this case))
    ports:
     - "4000:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./projects/video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"